/*
** See Copyright Notice In lang.h
** (X) ltoken.h (Autogenerated)
** This file was autogenerated by token.lang in tools
*/


#define FIRST_KEYWORD 1
#define  LAST_KEYWORD 22


typedef struct ltoken {
	enum ltokentype type;
	char *line;
	union {
		char const *s;
		llong i;
		lnumber n;
	};
} ltoken;


typedef enum ltokentype {
	TK_NONE = 0,
	TK_FUN = 1,
	TK_NIL = 2,
	TK_LOCAL = 3,
	TK_LET = 4,
	TK_FINALY = 5,
	TK_IN = 6,
	TK_FOR = 7,
	TK_WHILE = 8,
	TK_DO = 9,
	TK_BREAK = 10,
	TK_CONTINUE = 11,
	TK_LEAVE = 12,
	TK_IF = 13,
	TK_IFF = 14,
	TK_ELIF = 15,
	TK_THEN = 16,
	TK_ELSE = 17,
	TK_LOAD = 18,
	TK_TRUE = 19,
	TK_FALSE = 20,
	TK_STKGET = 21,
	TK_STKLEN = 22,
	TK_INTEGER = 23,
	TK_NUMBER = 24,
	TK_STRING = 25,
	TK_LETTER = 26,
	TK_WORD = 27,
	TK_QMARK = 28,
	TK_NEGATE = 29,
	TK_ASSIGN_QUESTION = 30,
	TK_ASSIGN = 31,
	TK_COLON = 32,
	TK_SEMI_COLON = 33,
	TK_DOT = 34,
	TK_COMMA = 35,
	TK_SQUARE_LEFT = 36,
	TK_SQUARE_RIGHT = 37,
	TK_CURLY_LEFT = 38,
	TK_CURLY_RIGHT = 39,
	TK_PAREN_LEFT = 40,
	TK_PAREN_RIGHT = 41,
	TK_MUL = 42,
	TK_DIV = 43,
	TK_MODULUS = 44,
	TK_ADD = 45,
	TK_SUB = 46,
	TK_RIGHT_SHIFT = 47,
	TK_LEFT_SHIFT = 48,
	TK_LESS_THAN = 49,
	TK_LESS_THAN_EQUAL = 50,
	TK_GREATER_THAN = 51,
	TK_GREATER_THAN_EQUAL = 52,
	TK_EQUALS = 53,
	TK_NOT_EQUALS = 54,
	TK_BIT_AND = 55,
	TK_BIT_OR = 56,
	TK_BIT_XOR = 57,
	TK_LOG_AND = 58,
	TK_LOG_OR = 59,
	TK_DOT_DOT = 60,
} ltokentype;


typedef struct ltokenintel {
	char *name;
	char  prec;
	lhash hash;
} ltokenintel;


lglobaldecl ltokenintel langX_tokenintel[] = {
	{"none",                 -2, 0},
	{"fun",                  -1, 2832955486},
	{"nil",                  -1, 228849900},
	{"local",                -1, 2621662984},
	{"let",                  -1, 1349190650},
	{"finally",              -1, 2618047400},
	{"in",                   -1, 1094220446},
	{"for",                  -1, 2901640080},
	{"while",                -1, 231090382},
	{"do",                   -1, 1646057492},
	{"break",                -1, 3378807160},
	{"continue",             -1, 2977070660},
	{"leave",                -1, 1416872128},
	{"if",                   -1, 959999494},
	{"iff",                  -1, 1943388448},
	{"elif",                 -1, 3232090307},
	{"then",                 -1, 3844270454},
	{"else",                 -1, 3183434736},
	{"load",                 -1, 3859241449},
	{"true",                 -1, 1303515621},
	{"false",                -1, 184981848},
	{"stkget",               -1, 2654528197},
	{"stklen",               -1, 1897109354},
	{"literal-integer",      -2, 0},
	{"literal-number",       -2, 0},
	{"literal-string",       -2, 0},
	{"literal-letter",       -2, 0},
	{"identifier",           -2, 0},
	{"?",                    -2, 0},
	{"!",                    -2, 0},
	{"?=",                   -2, 0},
	{"=",                    -2, 0},
	{":",                    -2, 0},
	{";",                    -2, 0},
	{".",                    -2, 0},
	{",",                    -2, 0},
	{"[",                    -2, 0},
	{"]",                    -2, 0},
	{"{",                    -2, 0},
	{"}",                    -2, 0},
	{"(",                    -2, 0},
	{")",                    -2, 0},
	{"*",                    11, 0},
	{"/",                    11, 0},
	{"%",                    11, 0},
	{"+",                    10, 0},
	{"-",                    10, 0},
	{">>",                   9, 0},
	{"<<",                   9, 0},
	{"<",                    8, 0},
	{"<=",                   8, 0},
	{">",                    8, 0},
	{">=",                   8, 0},
	{"==",                   7, 0},
	{"!=",                   7, 0},
	{"&",                    6, 0},
	{"|",                    5, 0},
	{"^",                    4, 0},
	{"&&",                   3, 0},
	{"||",                   2, 0},
	{"..",                   1, 0},
};


