// this file is manually autogenerated:
#include "raylib.h"

#define ELF_KEEPWARNINGS
#define ELF_NOLIBS
#include "elf.h"



#define PACK(xx) ((xx.r<<24)|(xx.g<<16)|(xx.b<<8)|(xx.a<<0))
#define UNPACK(xx) CLITERAL(Color){((xx>>24)&0xff),((xx>>16)&0xff),((xx>>8)&0xff),((xx>>0)&0xff)}


// void timeBeginPeriod(int x) {
// }


// void timeEndPeriod(int x) {
// }



typedef struct SoundObj {
	elf_Object obj;
	Sound sound;
} SoundObj;


elf_libfundecl int raylib_IsAudioDeviceReady(elf_ThreadState *R) {
	elf_locint(R,IsAudioDeviceReady());
	return 1;
}


elf_libfundecl int raylib_CloseAudioDevice(elf_ThreadState *R) {
	CloseAudioDevice();
	return 0;
}


elf_libfundecl int raylib_InitAudioDevice(elf_ThreadState *R) {
	InitAudioDevice();
	return 0;
}


elf_libfundecl int raylib_IsSoundPlaying(elf_ThreadState *R) {
	SoundObj *obj = (SoundObj *) elf_getobj(R,0);
	elf_locint(R,IsSoundPlaying(obj->sound));
	return 1;
}


elf_libfundecl int raylib_PlaySound(elf_ThreadState *R) {
	SoundObj *obj = (SoundObj *) elf_getobj(R,0);
	PlayAudioBuffer(obj->sound.stream.buffer);
	return 0;
}


elf_libfundecl int raylib_PauseSound(elf_ThreadState *R) {
	SoundObj *obj = (SoundObj *) elf_getobj(R,0);
	PauseSound(obj->sound);
	return 0;
}


elf_libfundecl int raylib_ResumeSound(elf_ThreadState *R) {
	SoundObj *obj = (SoundObj *) elf_getobj(R,0);
	ResumeSound(obj->sound);
	return 0;
}


elf_libfundecl int raylib_SetSoundVolume(elf_ThreadState *R) {
	SoundObj *obj = (SoundObj *) elf_getobj(R,0);
	SetSoundVolume(obj->sound,elf_getnum(R,1));
	return 0;
}


elf_libfundecl int raylib_SetSoundPitch(elf_ThreadState *R) {
	SoundObj *obj = (SoundObj *) elf_getobj(R,0);
	SetSoundPitch(obj->sound,elf_getnum(R,1));
	return 0;
}


elf_libfundecl int raylib_SetSoundPan(elf_ThreadState *R) {
	SoundObj *obj = (SoundObj *) elf_getobj(R,0);
	SetSoundPan(obj->sound,elf_getnum(R,1));
	return 0;
}


elf_libfundecl int raylib_IsSoundReady(elf_ThreadState *R) {
	SoundObj *obj = (SoundObj *) elf_getobj(R,0);
	elf_locint(R,IsSoundReady(obj->sound));
	return 1;
}


elf_libfundecl int raylib_LoadSoundAlias(elf_ThreadState *R) {
	SoundObj *obj = (SoundObj *) elf_getobj(R,0);
	SoundObj *alias = (SoundObj *) elf_newlocobj(R,sizeof(SoundObj));
	alias->sound = LoadSoundAlias(obj->sound);
	return 1;
}



elf_libfundecl int raylib_LoadSound(elf_ThreadState *R) {
 	Wave wave = LoadWave(elf_getstr(R,0)->c);
	Sound sound = LoadSoundFromWave(wave);
	SoundObj *obj = (SoundObj *) elf_newlocobj(R,sizeof(SoundObj));
	obj->sound = sound;
	UnloadWave(wave);
	return 1;
}


elf_libfundecl int raylib_GetFPS(elf_ThreadState *R) {
	elf_locint(R,GetFPS());
	return 1;
}


elf_libfundecl int raylib_IsKeyDown(elf_ThreadState *R) {
	elf_locint(R,IsKeyDown(elf_getint(R,0)));
	return 1;
}


elf_libfundecl int raylib_GetFrameTime(elf_ThreadState *R) {
	elf_locnum(R,GetFrameTime());
	return 1;
}


elf_libfundecl int raylib_IsMouseButtonDown(elf_ThreadState *R) {
	elf_locint(R,IsMouseButtonDown(elf_getint(R,0)));
	return 1;
}

elf_libfundecl int raylib_IsMouseButtonReleased(elf_ThreadState *R) {
	elf_locint(R,IsMouseButtonReleased(elf_getint(R,0)));
	return 1;
}

elf_libfundecl int raylib_IsMouseButtonUp(elf_ThreadState *R) {
	elf_locint(R,IsMouseButtonUp(elf_getint(R,0)));
	return 1;
}


elf_libfundecl int raylib_WindowShouldClose(elf_ThreadState *R) {
	elf_locint(R,WindowShouldClose());
	return 1;
}


elf_libfundecl int raylib_CloseWindow(elf_ThreadState *R) {
	(void) R;
	CloseWindow();
	return 0;
}


elf_libfundecl int raylib_InitWindow(elf_ThreadState *R) {
	int width = {(int)elf_getint(R,0)};
	int height = {(int)elf_getint(R,1)};
	char *title = {elf_getstr(R,2)->c};
	InitWindow(width,height,title);
	return 0;
}


elf_libfundecl int raylib_SetGameLoopFn(elf_ThreadState *R) {
	#if defined(PLATFORM_WEB)
	// emscripten_set_main_loop(UpdateDrawFrame, 0, 1);
	#endif
	return 0;
}


elf_libfundecl int raylib_GetMouseX(elf_ThreadState *R) {
	elf_locint(R,GetMouseX());
	return 1;
}


elf_libfundecl int raylib_GetMouseY(elf_ThreadState *R) {
	elf_locint(R,GetMouseY());
	return 1;
}


elf_libfundecl int raylib_SetTargetFPS(elf_ThreadState *R) {
	SetTargetFPS(elf_getint(R,0));
	return 0;
}


elf_libfundecl int raylib_EndDrawing(elf_ThreadState *R) {
	EndDrawing();
	return 0;
}


elf_libfundecl int raylib_BeginDrawing(elf_ThreadState *R) {
	BeginDrawing();
	return 0;
}


Vector2 raylib_tab2vec2(elf_ThreadState *R, elf_Table *tab) {
	return CLITERAL(Vector2) {
		elf_tabgetnum(tab,elf_newlocstr(R,"x")),
		elf_tabgetnum(tab,elf_newlocstr(R,"y")),
	};
}


elf_Table *raylib_putvec2(elf_ThreadState *R, Vector2 vec) {
	elf_Table *tab = elf_newloctab(R);
	elf_tabsetnumfld(tab,elf_newlocstr(R,"x"),vec.x);
	elf_tabsetnumfld(tab,elf_newlocstr(R,"y"),vec.y);
	elf_loctab(R,tab);
	return tab;
}


Camera2D raylib_tab2cam2d(elf_ThreadState *R, elf_Table *tab) {
	Camera2D result = {0};
	result.offset = raylib_tab2vec2(R,elf_tabgettab(tab,elf_newlocstr(R,"offset")));
	result.target = raylib_tab2vec2(R,elf_tabgettab(tab,elf_newlocstr(R,"target")));
	result.rotation = elf_tabgetnum(tab,elf_newlocstr(R,"rotation"));
	result.zoom = elf_tabgetnum(tab,elf_newlocstr(R,"zoom"));
	return result;
}


elf_libfundecl int raylib_BeginMode2D(elf_ThreadState *R) {
	elf_ensure(R->call->nx == 1);
	BeginMode2D(raylib_tab2cam2d(R,elf_gettab(R,0)));
	return 0;
}


elf_libfundecl int raylib_EndMode2D(elf_ThreadState *R) {
	EndMode2D();
	return 0;
}


elf_libfundecl int raylib_GetWorldToScreen2D(elf_ThreadState *R) {
	elf_ensure(R->call->nx == 2);
	raylib_putvec2(R,GetWorldToScreen2D(raylib_tab2vec2(R,elf_gettab(R,1)),raylib_tab2cam2d(R,elf_gettab(R,0))));
	return 1;
}


elf_libfundecl int raylib_GetScreenToWorld2D(elf_ThreadState *R) {
	elf_ensure(R->call->nx == 2);
	raylib_putvec2(R,GetScreenToWorld2D(raylib_tab2vec2(R,elf_gettab(R,1)),raylib_tab2cam2d(R,elf_gettab(R,0))));
	return 1;
}


elf_libfundecl int raylib_SetShapesTexture(elf_ThreadState *R) {
	elf_ensure(R->call->nx == 5);
	elf_Table *textab = elf_gettab(R,0);
	Texture2D tex = CLITERAL(Texture2D) {
		elf_tabgetint(textab,elf_newlocstr(R,"$id")),
		elf_tabgetint(textab,elf_newlocstr(R,"width")),
		elf_tabgetint(textab,elf_newlocstr(R,"height")),
		elf_tabgetint(textab,elf_newlocstr(R,"mipmaps")),
		elf_tabgetint(textab,elf_newlocstr(R,"format")),
	};
	Rectangle src = CLITERAL(Rectangle){
		elf_getint(R,1),elf_getint(R,2),elf_getint(R,3),elf_getint(R,4)
	};
	SetShapesTexture(tex,src);
	return 0;
}


elf_libfundecl int raylib_DrawFPS(elf_ThreadState *R) {
	DrawFPS(elf_getint(R,0),elf_getint(R,1));
	return 0;
}


elf_libfundecl int raylib_DrawRectangle(elf_ThreadState *R) {
	elf_ensure(R->call->nx == 5);
	elf_int color = elf_getint(R,4);
	DrawRectangle(
	elf_getnum(R,0),elf_getnum(R,1),
	elf_getnum(R,2),elf_getnum(R,3),UNPACK(color));
	return 0;
}


elf_libfundecl int raylib_DrawRectanglePro(elf_ThreadState *R) {
	elf_ensure(R->call->nx == 8);
	Rectangle rec = CLITERAL(Rectangle) {
		elf_getnum(R,0),elf_getnum(R,1),
		elf_getnum(R,2),elf_getnum(R,3)
	};
	Vector2 origin = CLITERAL(Vector2) {
		elf_getnum(R,4),elf_getnum(R,5),
	};
	float rotation = elf_getnum(R,6);
	elf_int color = elf_getint(R,7);
	DrawRectanglePro(rec,origin,rotation,UNPACK(color));
	return 0;
}


elf_libfundecl int raylib_LoadTexture(elf_ThreadState *R) {
	elf_ensure(R->call->nx == 1);
	char *filename = elf_getstr(R,0)->c;
	if (filename != lnil) {
		elf_Table *textab = elf_newloctab(R);
		Texture tex = LoadTexture(filename);
		elf_tabsetintfld(textab,elf_newlocstr(R,"$id"),tex.id);
		elf_tabsetintfld(textab,elf_newlocstr(R,"width"),tex.width);
		elf_tabsetintfld(textab,elf_newlocstr(R,"height"),tex.height);
		elf_tabsetintfld(textab,elf_newlocstr(R,"mipmaps"),tex.mipmaps);
		elf_tabsetintfld(textab,elf_newlocstr(R,"format"),tex.format);
		elf_loctab(R,textab);
	} else elf_locnil(R);
	return 1;
}


elf_libfundecl int raylib_ClearBackground(elf_ThreadState *R) {
	elf_ensure(R->call->nx == 1);
	elf_int color = elf_getint(R,0);
  	ClearBackground(UNPACK(color));
	return 0;
}


elf_libfundecl int raylib_DrawText(elf_ThreadState *R) {
	elf_ensure(R->call->nx == 5);
	char *text = elf_getstr(R,0)->c;
	float posx = elf_getnum(R,1);
	float posy = elf_getnum(R,2);
	float size = elf_getnum(R,3);
	elf_int color = elf_getint(R,4);
  	DrawText(text,posx,posy,size,UNPACK(color));
	return 0;
}


elf_libfundecl int raylib_load(elf_ThreadState *R) {
	elf_loginfo("raylib: loading...");

	elf_register(R,"elf.ray.IsAudioDeviceReady",raylib_IsAudioDeviceReady);
	elf_register(R,"elf.ray.CloseAudioDevice",raylib_CloseAudioDevice);
	elf_register(R,"elf.ray.InitAudioDevice",raylib_InitAudioDevice);
	elf_register(R,"elf.ray.SetSoundVolume",raylib_SetSoundVolume);
	elf_register(R,"elf.ray.LoadSound",raylib_LoadSound);
	elf_register(R,"elf.ray.LoadSoundAlias",raylib_LoadSoundAlias);
	elf_register(R,"elf.ray.PlaySound",raylib_PlaySound);
	elf_register(R,"elf.ray.SetSoundPan",raylib_SetSoundPan);
	elf_register(R,"elf.ray.SetSoundPitch",raylib_SetSoundPitch);
	elf_register(R,"elf.ray.IsSoundReady",raylib_IsSoundReady);
	elf_register(R,"elf.ray.IsSoundPlaying",raylib_IsSoundPlaying);
	elf_register(R,"elf.ray.PauseSound",raylib_PauseSound);
	elf_register(R,"elf.ray.ResumeSound",raylib_ResumeSound);



	elf_register(R,"elf.ray.GetFPS",raylib_GetFPS);
	elf_register(R,"elf.ray.GetFrameTime",raylib_GetFrameTime);
	elf_register(R,"elf.ray.IsKeyDown",raylib_IsKeyDown);
	elf_register(R,"elf.ray.IsMouseButtonDown",raylib_IsMouseButtonDown);
	elf_register(R,"elf.ray.IsMouseButtonReleased",raylib_IsMouseButtonReleased);
	elf_register(R,"elf.ray.IsMouseButtonUp",raylib_IsMouseButtonUp);
	elf_register(R,"elf.ray.GetWorldToScreen2D",raylib_GetWorldToScreen2D);
	elf_register(R,"elf.ray.GetScreenToWorld2D",raylib_GetScreenToWorld2D);

	elf_register(R,"elf.ray.GetMouseX",raylib_GetMouseX);
	elf_register(R,"elf.ray.GetMouseY",raylib_GetMouseY);
	elf_register(R,"elf.ray.InitWindow",raylib_InitWindow);
	elf_register(R,"elf.ray.CloseWindow",raylib_CloseWindow);
	elf_register(R,"elf.ray.WindowShouldClose",raylib_WindowShouldClose);
	elf_register(R,"elf.ray.SetShapesTexture",raylib_SetShapesTexture);
	elf_register(R,"elf.ray.LoadTexture",raylib_LoadTexture);
	elf_register(R,"elf.ray.BeginMode2D",raylib_BeginMode2D);
	elf_register(R,"elf.ray.EndMode2D",raylib_EndMode2D);
	elf_register(R,"elf.ray.SetTargetFPS",raylib_SetTargetFPS);

	elf_register(R,"elf.ray.BeginDrawing",raylib_BeginDrawing);
	elf_register(R,"elf.ray.EndDrawing",raylib_EndDrawing);
	elf_register(R,"elf.ray.ClearBackground",raylib_ClearBackground);
	elf_register(R,"elf.ray.DrawRectangle",raylib_DrawRectangle);
	elf_register(R,"elf.ray.DrawRectanglePro",raylib_DrawRectanglePro);
	elf_register(R,"elf.ray.DrawFPS",raylib_DrawFPS);
	elf_register(R,"elf.ray.DrawText",raylib_DrawText);

	elf_registerint(R,"elf.ray.LIGHTGRAY",PACK(LIGHTGRAY));
	elf_registerint(R,"elf.ray.GRAY",PACK(GRAY));
	elf_registerint(R,"elf.ray.DARKGRAY",PACK(DARKGRAY));
	elf_registerint(R,"elf.ray.YELLOW",PACK(YELLOW));
	elf_registerint(R,"elf.ray.GOLD",PACK(GOLD));
	elf_registerint(R,"elf.ray.ORANGE",PACK(ORANGE));
	elf_registerint(R,"elf.ray.PINK",PACK(PINK));
	elf_registerint(R,"elf.ray.RED",PACK(RED));
	elf_registerint(R,"elf.ray.MAROON",PACK(MAROON));
	elf_registerint(R,"elf.ray.GREEN",PACK(GREEN));
	elf_registerint(R,"elf.ray.LIME",PACK(LIME));
	elf_registerint(R,"elf.ray.DARKGREEN",PACK(DARKGREEN));
	elf_registerint(R,"elf.ray.SKYBLUE",PACK(SKYBLUE));
	elf_registerint(R,"elf.ray.BLUE",PACK(BLUE));
	elf_registerint(R,"elf.ray.DARKBLUE",PACK(DARKBLUE));
	elf_registerint(R,"elf.ray.PURPLE",PACK(PURPLE));
	elf_registerint(R,"elf.ray.VIOLET",PACK(VIOLET));
	elf_registerint(R,"elf.ray.DARKPURPLE",PACK(DARKPURPLE));
	elf_registerint(R,"elf.ray.BEIGE",PACK(BEIGE));
	elf_registerint(R,"elf.ray.BROWN",PACK(BROWN));
	elf_registerint(R,"elf.ray.DARKBROWN",PACK(DARKBROWN));
	elf_registerint(R,"elf.ray.WHITE",PACK(WHITE));
	elf_registerint(R,"elf.ray.BLACK",PACK(BLACK));
	elf_registerint(R,"elf.ray.BLANK",PACK(BLANK));
	elf_registerint(R,"elf.ray.MAGENTA",PACK(MAGENTA));
	elf_registerint(R,"elf.ray.WHITE",PACK(WHITE));
	elf_registerint(R,"elf.ray.RAYWHITE",PACK(WHITE));
	elf_loginfo("raylib: loaded all library functions");
	return 0;
}

