/*
** See Copyright Notice In lang.h
** lcode.h
** (C) Code Generation
*/


#define NO_JUMP (-1)


/* Contains list of false and true jumps
generated by some boolean expression. */
typedef struct Boolean {
	int *t,*f;
} Boolean;


/* Contains list of jumps generated
by a select statement, such as if else */
typedef struct Select {
	/* Conditional false jump instructions
	to be patched so that they jump to
	the next block or instruction */
	ByteId *jz;

	/* list of exit jump instructions from
	each block to be patched */
	ByteId *j;
} Select;


typedef struct Loop {
	ByteId x,e;
	/* list of false jumps to patch */
	ByteId *f;
} Loop;


void langC_load(FileState *fs, char * loc, int x);


void langC_beginif(FileState *fs, char * line, Select *s, int x);
void langC_addelif(FileState *fs, char * line, Select *s, int x);
void langC_addelse(FileState *fs, char * line, Select *s);
void langC_closeif(FileState *fs, char * line, Select *s);

void langC_beginloop(FileState *fs, char * line, Loop *loop, int x, int r);
void langC_closeloop(FileState *fs, char * line, Loop *loop);
