/*
** See Copyright Notice In lang.h
** (X) ltoken.h (Autogenerated)
** This file was autogenerated by token.lang in tools
*/


#define FIRST_KEYWORD 1
#define  LAST_KEYWORD 24


typedef struct ltoken {
	enum ltokentype type;
	llineid line;
	unsigned int eol: 1;
	union {
		char *s;
		llongint i;
		lnumber n;
	};
} ltoken;


typedef enum ltokentype {
	TK_NONE                 = 0,
	TK_ENUM                 = 1,
	TK_FUN                  = 2,
	TK_NIL                  = 3,
	TK_LOCAL                = 4,
	TK_LET                  = 5,
	TK_FINALLY              = 6,
	TK_IN                   = 7,
	TK_FOR                  = 8,
	TK_FOREACH              = 9,
	TK_WHILE                = 10,
	TK_DO                   = 11,
	TK_BREAK                = 12,
	TK_CONTINUE             = 13,
	TK_LEAVE                = 14,
	TK_IF                   = 15,
	TK_IFF                  = 16,
	TK_ELIF                 = 17,
	TK_THEN                 = 18,
	TK_ELSE                 = 19,
	TK_LOAD                 = 20,
	TK_TRUE                 = 21,
	TK_FALSE                = 22,
	TK_STKGET               = 23,
	TK_STKLEN               = 24,
	TK_INTEGER              = 25,
	TK_NUMBER               = 26,
	TK_STRING               = 27,
	TK_LETTER               = 28,
	TK_WORD                 = 29,
	TK_QMARK                = 30,
	TK_NEGATE               = 31,
	TK_ASSIGN_QUESTION      = 32,
	TK_ASSIGN               = 33,
	TK_COLON                = 34,
	TK_SEMI_COLON           = 35,
	TK_DOT                  = 36,
	TK_COMMA                = 37,
	TK_SQUARE_LEFT          = 38,
	TK_SQUARE_RIGHT         = 39,
	TK_CURLY_LEFT           = 40,
	TK_CURLY_RIGHT          = 41,
	TK_PAREN_LEFT           = 42,
	TK_PAREN_RIGHT          = 43,
	TK_MUL                  = 44,
	TK_DIV                  = 45,
	TK_MODULUS              = 46,
	TK_ADD                  = 47,
	TK_SUB                  = 48,
	TK_RIGHT_SHIFT          = 49,
	TK_LEFT_SHIFT           = 50,
	TK_LESS_THAN            = 51,
	TK_LESS_THAN_EQUAL      = 52,
	TK_GREATER_THAN         = 53,
	TK_GREATER_THAN_EQUAL   = 54,
	TK_EQUALS               = 55,
	TK_NOT_EQUALS           = 56,
	TK_BIT_AND              = 57,
	TK_BIT_OR               = 58,
	TK_BIT_XOR              = 59,
	TK_LOG_AND              = 60,
	TK_LOG_OR               = 61,
	TK_DOT_DOT              = 62,
} ltokentype;


typedef struct ltokenintel {
	char *name;
	char prec;
	lhashid hash;
} ltokenintel;


lglobaldecl ltokenintel langX_tokenintel[] = {
	{"none",                 -2, 0},
	{"enum",                 -1, 2171383808},
	{"fun",                  -1, 2832955486},
	{"nil",                  -1, 228849900},
	{"local",                -1, 2621662984},
	{"let",                  -1, 1349190650},
	{"finally",              -1, 2618047400},
	{"in",                   -1, 1094220446},
	{"for",                  -1, 2901640080},
	{"foreach",              -1, 3076491097},
	{"while",                -1, 231090382},
	{"do",                   -1, 1646057492},
	{"break",                -1, 3378807160},
	{"continue",             -1, 2977070660},
	{"leave",                -1, 1416872128},
	{"if",                   -1, 959999494},
	{"iff",                  -1, 1943388448},
	{"elif",                 -1, 3232090307},
	{"then",                 -1, 3844270454},
	{"else",                 -1, 3183434736},
	{"load",                 -1, 3859241449},
	{"true",                 -1, 1303515621},
	{"false",                -1, 184981848},
	{"stkget",               -1, 2654528197},
	{"stklen",               -1, 1897109354},
	{"literal-integer",      -2, 0},
	{"literal-number",       -2, 0},
	{"literal-string",       -2, 0},
	{"literal-letter",       -2, 0},
	{"identifier",           -2, 0},
	{"?",                    -2, 0},
	{"!",                    -2, 0},
	{"?=",                   -2, 0},
	{"=",                    -2, 0},
	{":",                    -2, 0},
	{";",                    -2, 0},
	{".",                    -2, 0},
	{",",                    -2, 0},
	{"[",                    -2, 0},
	{"]",                    -2, 0},
	{"{",                    -2, 0},
	{"}",                    -2, 0},
	{"(",                    -2, 0},
	{")",                    -2, 0},
	{"*",                    11, 0},
	{"/",                    11, 0},
	{"%",                    11, 0},
	{"+",                    10, 0},
	{"-",                    10, 0},
	{">>",                   9, 0},
	{"<<",                   9, 0},
	{"<",                    8, 0},
	{"<=",                   8, 0},
	{">",                    8, 0},
	{">=",                   8, 0},
	{"==",                   7, 0},
	{"!=",                   7, 0},
	{"&",                    6, 0},
	{"|",                    5, 0},
	{"^",                    4, 0},
	{"&&",                   3, 0},
	{"||",                   2, 0},
	{"..",                   1, 0},
};


